server: # Server 服务端相关配置
  port: 8081 # 端口
  context-path: /video # 访问路径
  tomcat: # Server - tomcat tomcat相关配置
    uri-encoding: UTF-8 # tomcat
mybatis: # mybatis 配置
  type-aliases-package: xyz.xnmq.inf.*.mapper # mapper文件位置，还需要配置@Mapper或者@MapperScan注解使用
  mapper-locations: classpath:mybatis/mapper/*/*.xml # xml文件位置

spring:
  jpa:
    database: mysql
    show-sql: true # 是否输出sql
    generate-ddl: false
    hibernate.ddl-auto: update
    hibernate.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource: # 数据源配置 使用阿里巴巴的 druid 数据源
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1qaz@WSX
    url: jdbc:mysql://132.232.106.103:3306/video-dev?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull&amp;useLocalSessionState=true
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    maximum-pool-size: 100
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
  # Redis 配置
  redis:
    database: 1 # Redis 数据库索引(默认为0)
    host: 132.232.106.103 # Redis 服务器地址
    port: 6379 # Redis 端口
    password: 7ujm*IK< # Redis 连接密码 默认为空
    pool: # Redis 连接池配置
      max-active: 8 # 连接池最大连接数(使用负值表示没有限制)
      max-wait: -1 #  连接池最大阻塞等待时间(使用负值表示没有限制)
      max-idle: 8 # 连接池最大空闲连接
      min-idle: 2 # 连接池最小空闲连接
    timeout: 0 # 连接超时时间(毫秒)












