server: # Server 服务端相关配置
  port: 8081 # 端口
  context-path: /video # 访问路径
  tomcat: # Server - tomcat tomcat相关配置
    uri-encoding: UTF-8 # tomcat

spring:
  profiles:
    active: dev
  jpa:
    database: mysql
    show-sql: true # 是否输出sql
    generate-ddl: false
    hibernate.ddl-auto: update
    hibernate.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  http:
    multipart:
      max-file-size: 5Mb
      max-request-size: 5Mb

mybatis: # mybatis 配置
  type-aliases-package: xyz.xnmq.inf.*.mapper # mapper文件位置，还需要配置@Mapper或者@MapperScan注解使用
  mapper-locations: classpath:mybatis/mapper/*/*.xml # xml文件位置











